### ISSUE TITLE
[Request] Kill commands should copy sexp to the clipboard

### ISSUE THREAD

**Issue by crinklywrappr** [BetterThanTomorrow/calva-paredit#7]
It's a pretty common use case for me - kill a form and then paste it a somewhere else or a few different places.  Currently can't do this.

**Comment by PEZ** [comment]
Thanks. Will look at this. I guess the hardest part will be to figure out if I dare simply do as you suggest or if that will surprise other users too much. I'm not a big fan of settings. :smile:

**Comment by crinklywrappr** [comment]
If there were yank/copy (forward/backward) commands then I could make do with that. :-)

**Comment by PEZ** [comment]
Yes, that's one way to do it. Maybe a ”yank board” could be populated by the kill commands, and then a command that pasted that content?

**Comment by crinklywrappr** [comment]
I am staunchly opposed to two separate clipboards.  :angry: lol

I meant that additional commands could be added eg

"paredit.yankSexpForward", "shift+windows+y"
"paredit.yankSexpBackward", "windows+y"


They would work over forms in the exact same way as the kill commands but would copy to the clipboard instead of deletion.  This would add copy without changing the current kill functionality or adding a new setting.

**Comment by PEZ** [comment]
I have my background in `vi` where you have tons of clipboards and it is wonderful. :smile:

New commands make sense. I hesitate because it means more for me to maintain and more to learn for the user, but it seems that copying and cutting with Paredit commands really fits the purpose of this extension.

**Comment by PEZ** [comment]
There is a new version of Calva Paredit, `0.1.11`which adds a *Copy* and a *Cut* command for each navigation command + the command for selecting the current top level form.

Please give it a try!

**Comment by crinklywrappr** [comment]
Thanks, man!  I tried them out and This will help a lot!

**Comment by PEZ** [comment]
Happy it works!

I found your vscode settings repo and notice you are also a `vi` guy (well, I am not really, these days, but anyway). Found this amount the `vim` key bindings, that I wonder  a bit about:

```json
        {
            "before": ["<leader>", "k", "y"],
            "commands": ["paredit.forwardSexp",
                "paredit.backwardSexp",
                "paredit.yankForwardSexp"],
            "when": "editorTextFocus && !editorReadonly"
        },
```

Is this stringing the commands `forwardSexp`, `backwardSexp`, and `yankForwardSexp` and executing them after each other? If so, why? I have a guess, if the cursor is not adjacent to the forward sexp, you don't want to have the whitespace yanked?

I was thinking about this while adding the commands, if I should include the whitespace or not. As you noticed (if my guess is correct), I chose not to do the extra work of ignoring the whitespace. In the spirit of Paredit, maybe it is worth doing it structurally… For you, with the `vim` bindings, it is easy to solve it for yourself, but otherwise it is a bit of a bother, me thinks. Your thoughts?

**Comment by crinklywrappr** [comment]
I agree with that ... it would be preferable for most people.  However, I would still string these commands together.  My reason for doing so is connected to Issue #6 .  If I take a simple form, eg `myvar`, place the cursor on `v`, and then execute `"paredit.yankForwardSexp"` I expect the form which my cursor is on to be yanked.  Currently the command yanks `var` instead of `myvar`.

Maybe there is a better sequence of commands to chain together and achieve the same goal?

**Comment by PEZ** [comment]
I think that with some little more help from `paredit.js` this would be easier to implement. I'll ponder some about what kind of help that would be and maybe I'll send a PR to that project. Need to see that someone answers our current issued filed there, first so I know it is worth the time spent to work on a PR.
